# Generated by Django 3.2.12 on 2022-05-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('RD', '공부 준비 중'), ('SC', '대본 공부 중'), ('WR', '에세이 쓰는 중'), ('SP', '말하기 연습 중'), ('DN', '공부 완료'), ('RV', '복습 중')], max_length=2)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('essays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lectures.essay')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lectures.video')),
            ],
        ),
    ]
